# Generated by Django 6.0.5 on 2026-09-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('pb', 'public'), ('fol', 'followers')], default='followers', max_length=3),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follower_id', to=settings.AUTH_USER_MODEL)),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='following_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
